import { useMemo } from 'react'
import type { Place } from '../types/places'

// Static import — places.json is generated by scripts/processGeodata.ts
import placesData from '../data/places.json'

const allPlaces = placesData as Place[]

export function useParshaPlaces(parshaId: string | null): Place[] {
  return useMemo(() => {
    if (!parshaId) return []
    return allPlaces.filter((p) => p.parshas.includes(parshaId))
  }, [parshaId])
}
